// <auto-generated />
using System;
using LibraryManager.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManager.API.Migrations
{
    [DbContext(typeof(LibraryDataContext))]
    [Migration("20251029140447_AddRestrictDeleteToRentals")]
    partial class AddRestrictDeleteToRentals
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("LibraryManager.Shared.Models.Book", b =>
                {
                    b.Property<int>("InventoryNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryNumber");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryManager.Shared.Models.Reader", b =>
                {
                    b.Property<int>("ReaderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReaderNumber");

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("LibraryManager.Shared.Models.Rental", b =>
                {
                    b.Property<int>("RentalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReaderNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("RentalDate")
                        .HasColumnType("TEXT");

                    b.HasKey("RentalID");

                    b.HasIndex("InventoryNumber");

                    b.HasIndex("ReaderNumber");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("LibraryManager.Shared.Models.Rental", b =>
                {
                    b.HasOne("LibraryManager.Shared.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("InventoryNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManager.Shared.Models.Reader", "Reader")
                        .WithMany()
                        .HasForeignKey("ReaderNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Reader");
                });
#pragma warning restore 612, 618
        }
    }
}
